services:
  mongo-recommendation:
    container_name: recommendationdb
    image: mongo:8
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017
    volumes:
      - ./../../../../data/mongo-recommendationdb:/data/db
    networks:
      - sonerapp

  recommendation:
    image: soner9/recommendation:v5
    container_name: recommendation
    ports:
      - 7002:7002
    environment:
      - SPRING_APPLICATION_NAME=recommendation
      - SPRING_DATA_MONGODB_HOST=mongo-recommendation
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:7071
    env_file:
      - ./../../global.env
    depends_on:
      mongo-recommendation:
        condition: service_healthy
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sonerapp
