spring:
  application:
    name: gatewayserver
  config:
    import:
      - optional:configserver:http://localhost:7071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      access: read-only

logging:
  level:
    "[org.springframework]": debug
