spring:
  application:
    name: gatewayserver
  config:
    import:
      - optional:configserver:http://localhost:7071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/master/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      access: read-only

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 50
