spring:
  application:
    name: eurekaserver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  config:
    import:
      - optional:configserver:http://localhost:7071

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
          - health
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
