services:
  product-aggregator:
    image: soner9/product-aggregator:v4
    container_name: product-aggregator
    ports:
      - 7000:7000
    environment:
      - SPRING_APPLICATION_NAME=product-aggregator
    env_file:
      - ./../../global.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sonerapp
