spring:
  application:
    name: product
  config:
    import:
      - optional:configserver:http://localhost:7071
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      username: root
      password: example
      host: localhost
      port: 27017
      database: productdb
      authentication-database: admin
  cloud:
    function:
      definition: productHandler
    stream:
      bindings:
        productHandler-in-0:
          destination: product
          group: ${spring.application.name}
          consumer:
            max-attempts: 5

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs

server:
  port: 7001

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
          - health
          - info
          - shutdown
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7070/eureka/
