spring:
  application:
    name: product-aggregator
  config:
    import:
      - optional:configserver:http://localhost:7071
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs

server:
  port: 7000

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
          - health
