spring:
  application:
    name: product-aggregator
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
server:
  port: 7000
