spring:
  application:
    name: configserver
  profiles:
    active:
      - native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations:
            - "classpath:/config"

server:
  port: 7071

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: PUA6cHajW72qbGZ3aiuZZipH0sBYYStY+oKGc9fn45MhK21ZhTQ2WyP1dZg=
