include:
  - ./rabbitmq/compose.yml
  - ./configserver/compose.yml
  - ./eurekaserver/compose.yml
  - ./gatewayserver/compose.yml
  - ./microservices/product/compose.yml
  - ./microservices/product-aggregator/compose.yml
  - ./microservices/recommendation/compose.yml
  - ./microservices/review/compose.yml

networks:
  sonerapp:
    driver: bridge
