spring:
  application:
    name: review
  config:
    import:
      - optional:configserver:http://localhost:7071
server:
  port: 7003

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
          - health
