services:
  product-aggregator:
    image: soner9/product-aggregator:v7
    container_name: product-aggregator
    ports:
      - 7000:7000
    healthcheck:
      test: "curl --fail --silent localhost:7000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      - SPRING_APPLICATION_NAME=product-aggregator
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:7071
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:7070/eureka/
    env_file:
      - ./../../global.env
    depends_on:
      eurekaserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sonerapp
